# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bX_s-akiIXAvkht5Pp5DQ4yvUFSzMkwY
"""

import numpy as np

student_marks = [22,24,27,21,23,29]
print(student_marks)
print(type(student_marks))

arr1 = np.array(list)
print(arr1)
# print(type(arr1))

arr2 = np.array([10,20,30,40])
print(arr2)

# 2d array
arr3 = np.array([[10,20,30,40],[45,70,34,38],[1,2,3,4]])
print(arr3)

#3d array
arr4 = np.array([[[10,20,30],[25,35,45]],[[17,18,19],[33,45,77]],[[1,2,3],[4,5,6]]])
print(arr4)

arr5 = np.zeros((4,4),dtype=int)
print(arr5)

arr6 = np.zeros(3,dtype=int)
print(arr6)

arr7 = np.zeros((3,4,4),dtype=int)
print(arr7)

arr7 = np.ones(5)
print(arr7)

arr7 = np.ones(5,dtype=int)
print(arr7)

import numpy as np

arr8 = np.array([
    [[1,  2,  3,  4],
     [5,  6,  7,  8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]],

    [[17, 18, 19, 20],
     [21, 22, 23, 24],
     [25, 26, 27, 28],
     [29, 30, 31, 32]],

    [[33, 34, 35, 36],
     [37, 38, 39, 40],
     [41, 42, 43, 44],
     [45, 46, 47, 48]],

    [[49, 50, 51, 52],
     [53, 54, 55, 56],
     [57, 58, 59, 60],
     [61, 62, 63, 64]],

    [[65, 66, 67, 68],
     [69, 70, 71, 72],
     [73, 74, 75, 76],
     [77, 78, 79, 80]],

    [[81, 82, 83, 84],
     [85, 86, 87, 88],
     [89, 90, 91, 92],
     [93, 94, 95, 96]],

    [[97,  98,  99, 100],
     [101, 102, 103, 104],
     [105, 106, 107, 108],
     [109, 110, 111, 112]],

    [[113, 114, 115, 116],
     [117, 118, 119, 120],
     [121, 122, 123, 124],
     [125, 126, 127, 128]],

    [[129, 130, 131, 132],
     [133, 134, 135, 136],
     [137, 138, 139, 140],
     [141, 142, 143, 144]],

    [[145, 146, 147, 148],
     [149, 150, 151, 152],
     [153, 154, 155, 156],
     [157, 158, 159, 160]]
])

print(arr8)

# Identity matrix
arr9 = np.identity(3,dtype=int)
print(arr9)

arr10 = np.eye(4,dtype=int)
print(arr10)

# defining row and column
arr10 = np.eye(3,4,dtype=int)
print(arr10)

# Identity of 3d array
arr11 = np.tile(np.eye(2,3),(2,1,1))
print(arr11)

arr12 = np.arange(10)
print(arr12)

arr13=np.arange(5,25)
print(arr13)

arr14=np.arange(5,51,5)
print(arr14)

arr15 = np.linspace(0,100,5,dtype=int)
print(arr14)

arr16 = arr2.copy();
print(arr16)

print(arr2)
print(arr2.shape)

print(arr3)
print(arr3.shape)

print(arr4)
print(arr4.shape)

print(arr2)
print(arr2.ndim)

print(arr3.ndim)

print(arr4.ndim)

print(arr2.size)

print(arr3.size)

print(arr4.size)

print(arr1.itemsize,"byte")

print(arr2)
arr17 = arr2.astype(float)
print(arr17)
print(arr17.itemsize,"bytes")